### ISSUE TITLE
Connection closed by peer 

### ISSUE THREAD

**Issue by jkl375** [lucidrains/ring-attention-pytorch#10]
when I set use_cuda = True, and set
```
  os.environ['MASTER_ADDR'] = '127.0.0.1'
  os.environ['MASTER_PORT'] = '1234'
```
the error as follow:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/app/assert.py", line 87, in start
    ring_out = ddp_ring_attention_net(seq)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/distributed.py", line 1509, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/distributed.py", line 1345, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/app/ring_attention_pytorch/ring_attention.py", line 568, in forward
    x = attn(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/app/ring_attention_pytorch/ring_attention.py", line 368, in forward
    out = ring_flash_attn_cuda(
  File "<@beartype(ring_attention_pytorch.ring_flash_attention_cuda.ring_flash_attn_cuda) at 0x7fdd828c4ee0>", line 214, in ring_flash_attn_cuda
  File "/app/ring_attention_pytorch/ring_flash_attention_cuda.py", line 752, in ring_flash_attn_cuda
    return ring_flash_attn_cuda_(q, k, v, mask, causal, bucket_size, ring_reduce_col, striped_ring_attn, max_lookback_seq_len, ring_size)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 551, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/app/ring_attention_pytorch/ring_flash_attention_cuda.py", line 526, in forward
    for (ring_rank, is_last), ((kv, mask), (receive_kv, receive_mask)) in ring_pass_fn(kv, mask, receive_buffers = (receive_kv, receive_mask), max_iters = max_ring_passes, ring_size = ring_size):
  File "/app/ring_attention_pytorch/ring.py", line 127, in all_ring_pass
    new_tensor, new_receive_buffer = one_ring_pass(tensor, receive_buffer, ring_size)
  File "/app/ring_attention_pytorch/ring.py", line 88, in ring_pass
    send_and_receive_(x, receive_buffer, circular_rank_right(ring_size = ring_size), circular_rank_left(ring_size = ring_size))
  File "/app/ring_attention_pytorch/ring.py", line 69, in send_and_receive_
    dist.recv(receive_buffer, receive_from_rank)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1680, in recv
    pg.recv([tensor], src, tag).wait()
RuntimeError: [/opt/pytorch/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [172.24.0.2]:34966
```

**Comment by lucidrains** [comment]
@jkl375 try again on the latest version, should be fixed!
